FROM node:20-alpine

ARG FOLDER=/app

COPY . /app

RUN apk add --no-cache python3 py3-virtualenv && \
    chmod +x /app/n8n-script.sh && \
    chmod +x /app/restart-n8n.sh

ENV N8N_USER_FOLDER=/app/n8n-server

WORKDIR ${FOLDER}

RUN npm install 

EXPOSE 5678

CMD [ "sh", "./n8n-script.sh" ]

