FROM node:20-alpine

ARG FOLDER=/app

RUN apk add --update --no-cache python3 tini

COPY . /app

RUN chown -R 1000:1000 ${FOLDER} && \
    chmod +x $FOLDER/restart-n8n.sh

ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

ENV N8N_RUNNERS_ENABLED=true

EXPOSE 5678

USER 1000:1000

WORKDIR ${FOLDER}

ENTRYPOINT ["tini", "--"]

CMD ["sh", "-c", "exec npx nodemon --signal SIGTERM --watch ./nodes/ --watch ./credentials/ --ext ts,js,json --exec 'sh ./restart-n8n.sh'"]