apiVersion: apps/v1
{{- if eq .Values.stage "development"}}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  {{- if eq .Values.stage "development"}}
  serviceName: app
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: diploi-pull-secret
      initContainers:
        - name: create-db
          image: postgres:17.2
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: PGPASSWORD
              value: "{{ .Values.envMap.DB_POSTGRESDB_PASSWORD.value }}"
          command:
            - sh
            - -c
            - |
              set -e

              echo "Checking if database {{ .Values.envMap.DB_POSTGRESDB_DATABASE.value }} exists..."

              if psql "host={{ .Values.envMap.DB_POSTGRESDB_HOST.value }} \
                      user={{ .Values.envMap.DB_POSTGRESDB_USER.value }} \
                      dbname=postgres \
                      connect_timeout=3" \
                  -tAc "SELECT 1 FROM pg_database WHERE datname='{{ .Values.envMap.DB_POSTGRESDB_DATABASE.value }}'" \
                | grep -q 1; then
                echo "Database already exists, exiting initContainer"
                exit 0
              fi
              
              echo "Database does not exist, creating database {{ .Values.envMap.DB_POSTGRESDB_DATABASE.value }}..."
              
              psql "host={{ .Values.envMap.DB_POSTGRESDB_HOST.value }} \
                    user={{ .Values.envMap.DB_POSTGRESDB_USER.value }} \
                    dbname=postgres \
                    connect_timeout=3" \
                -c "CREATE DATABASE {{ .Values.envMap.DB_POSTGRESDB_DATABASE.value }}"
        {{- if eq .Values.stage "development"}}
        - name: install-dependencies
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          command: ['npm', 'install']
          workingDir: /app{{ .Values.folder }}
          env:
          - name: N8N_ENV
            value: development
          volumeMounts:
            - name: app-mount
              mountPath: /app
        {{- end }}
      containers:
        - name: app
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5678
          {{- if eq .Values.stage "development" }}
          workingDir: /app{{ .Values.folder }}
          {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            - name: APP_PUBLIC_URL
              value: {{ .Values.hosts.app }}
            - name: WEBHOOK_URL
              value: https://{{ .Values.hosts.app }}
            - name: STAGE
              value: {{ .Values.stage }}
          {{- if eq .Values.stage "development" }}
            - name: N8N_USER_FOLDER
              value: /app{{ .Values.folder }}/n8n-server
          {{- end }}
          volumeMounts:
            {{- if hasKey .Values.storage "code" }}
            - name: app-mount
              mountPath: /app
            {{- end }}
      volumes:
        {{- if hasKey .Values.storage "code" }}
        - name: app-mount
          hostPath:
            path: {{ .Values.storage.code.hostPath }}
        {{- end }}